
=head1 NAME

=over 4

=item B<golden> - Databank flat files entry retriever

=back

=head1 SYNOPSIS

=over 4

=item B<golden> [B<-achil>] [B<-o> F<file>] [B<-f> F<file1> F<file2> F<file3> F<...> F<fileN>] E<lt>F<dbase>:F<name> F<dbase>:F<name> ... F<dbase>:F<name>E<gt>

=back

=head1 OPTIONS

Following command line options are allowed:

=over 4

=item -a

Search entry by accession number.

=item -c

Check entry existence (do not display it, if found).

=item -h

Usage display.

=item -i

Search entry by entry name.

=item -l

List all available databanks.

=item -o F<file>

Output result in F<file>.

=item -f F<file1> F<file2> F<file3> F<...> F<fileN>

 Input query values are read from F<file1> F<file2> F<file3> F<...> F<fileN>.
 These files must contain F<dbase>:F<name> information separated by \n.
 Query results are sorted in the same order as query values are provided in input.
 See the example part for more information on file format.

=back

=head1 DESCRIPTION

B<golden> is a databank flat files entry retriever.

It search for entry F<name> in F<dbase> indexes. By default, both
accession number and entry names are searched (in that order), and the
first matching F<name> is displayed.

Search can be restricted to a single index type by setting one of the
following flags: B<-a> for accession numbers or B<-i> for entry
names. Setting both flags will restore the default search behaviour.

=head1 EXAMPLES

=over 4

=item golden genbank:mmvasp embl:stuff1 embl:stuff2 genbank:otherAC uniprot:anotherLocus embl:stuff3

Search:
 entries named `mmvasp' and 'otherAC' in `genbank' databank,
 entries named 'stuff1', 'stuff2' and 'stuff3 in 'embl' databank' 
 entry named 'anotherLocus' in 'uniprot' databank.

Search is performed in both entry names and accession number indexes (default = both).

=item golden -i genbank:mmvasp embl:stuff1 embl:stuff2 genbank:otherAC uniprot:anotherLocus embl:stuff3

Same search but in entry names indexes only.

=item golden -l

List all available (indexed) databanks.

=item golden -f file1 file2 file3

Search all entries listed in file1, file2 and file3.

File format must be as follows:
 genbank:mmvasp\n
 embl:stuff1\n
 embl:stuff2\n
 genbank:otherAC\n
 uniprot:anotherLocus\n
 embl:stuff3

=back

=head1 ENVIRONMENT

=over 10

=item GOLDENDATA

Used to specify an alternate golden indexes directory.

GOLDENDATA index directory must contain:
  1- index files generated by goldin (.acx and/or .icx, .dbx) or links to them.\n
  2- subdirectories (or links to subdirectories) with databanks base name and containing flat files.

For example, if you indexed uniprot with goldin, you should have :
  - index files (uniprot.acx and/or uniprot.icx plus uniprot.dbx)\n
  - a directory uniprot containing uniprot databank flat files.

It is crucial to keep consistency between index files name and name of the directory that contains your databank's flat files.

=back

=head1 SEE ALSO

=over 4

=item B<goldin>(1)

=back

=head1 AUTHOR

Nicolas Joly (njoly@pasteur.fr), Veronique Legrand (vlegrand@pasteur.fr) Institut Pasteur.
